const NotificationEvent = Object.freeze({
    // 프로젝트 회원추가, 대상 회원만
    MEMBER_ENROLL_ACCEPT: "MEMBER_ENROLL_ACCEPT",
    // 이슈상태변경(열림, 닫힘), 작성자에게만
    ISSUE_STATE_CHANGED: "ISSUE_STATE_CHANGED",
    // 이슈코멘트(언급), 언급 대상 유저에게만
    NEW_COMMENT: "NEW_COMMENT",
    // 이슈 담당자 변경 시, 변경 전 담당자 ex) a -> b 로 변경 시 a에게 알림감.
    ISSUE_ASSIGNEE_CHANGED: "ISSUE_ASSIGNEE_CHANGED",

    NEW_ISSUE: "NEW_ISSUE",
    NEW_POSTING: "NEW_POSTING",
    NEW_PULL_REQUEST: "NEW_PULL_REQUEST",
    PULL_REQUEST_STATE_CHANGED: "PULL_REQUEST_STATE_CHANGED",
    NEW_REVIEW_COMMENT: "NEW_REVIEW_COMMENT",
    MEMBER_ENROLL_REQUEST: "MEMBER_ENROLL_REQUEST",
    PULL_REQUEST_MERGED: "PULL_REQUEST_MERGED",
    ISSUE_REFERRED_FROM_COMMIT: "ISSUE_REFERRED_FROM_COMMIT",
    PULL_REQUEST_COMMIT_CHANGED: "PULL_REQUEST_COMMIT_CHANGED",
    NEW_COMMIT: "NEW_COMMIT",
    PULL_REQUEST_REVIEW_STATE_CHANGED: "PULL_REQUEST_REVIEW_STATE_CHANGED",
    ISSUE_BODY_CHANGED: "ISSUE_BODY_CHANGED",
    ISSUE_REFERRED_FROM_PULL_REQUEST: "ISSUE_REFERRED_FROM_PULL_REQUEST",
    REVIEW_THREAD_STATE_CHANGED: "REVIEW_THREAD_STATE_CHANGED",
    ORGANIZATION_MEMBER_ENROLL_REQUEST: "ORGANIZATION_MEMBER_ENROLL_REQUEST",
    COMMENT_UPDATED: "COMMENT_UPDATED",
    ISSUE_MOVED: "ISSUE_MOVED",
    ISSUE_SHARER_CHANGED: "ISSUE_SHARER_CHANGED",
    ISSUE_LABEL_CHANGED: "ISSUE_LABEL_CHANGED",
    ISSUE_MILESTONE_CHANGED: "ISSUE_MILESTONE_CHANGED",
    POSTING_BODY_CHANGED: "POSTING_BODY_CHANGED",
    RESOURCE_DELETED: "RESOURCE_DELETED",
    ORGANIZATION_MEMBER_ENROLL_ACCEPT: "ORGANIZATION_MEMBER_ENROLL_ACCEPT"
});

const NotificationType = Object.freeze({
    PUSH: "PUSH"
});

const NotificationPlatform = Object.freeze({
    KAKAOWORK: "KAKAOWORK",
})

const NotificationStatus = Object.freeze({
    CREATED:"CREATED", PEND:"PEND", SUCCESS:"SUCCESS", FAIL:"FAIL"
})

module.exports = {
    NotificationEvent, NotificationType, NotificationPlatform, NotificationStatus
}  