version: '3.8'

services:
  app:
    image: node:20.11.0
    container_name: notif
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npx prisma generate && npm run start:local"
